name: TAXII Docs
markdown: redcarpet
highlighter: pygments

copyright: The MITRE Corporation

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', "Rakefile", "LICENSE"]

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

encoding: utf-8

redirects: yes

gems:
 - jekyll-redirect-from
