name: TAXII Docs
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

copyright: The MITRE Corporation

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', "Rakefile", "LICENSE"]

encoding: utf-8

redirects: yes

gems:
 - jekyll-redirect-from
